  "pg_service_charge_bdt": "4.83",
  "amount_original": "230.00",
  "gateway_fee": null,
  "pg_service_charge_usd": "Not-Available",
  "pg_card_bank_name": "Not Available",
  "pg_card_bank_country": "Not Available",
  "card_number": "1234XXXXXXXXX123",
  "card_holder": null,
  "status_code": "2",
  "pay_status": "Successful",
  "success_url": "http://127.0.0.1:8000/success",
  "fail_url": "http://127.0.0.1:8000/fail",
  "cus_name": "customer",
  "cus_email": "a@gmail.com",
  "cus_phone": "01964359945",
  "currency_merchant": "BDT",
  "convertion_rate": null,
  "ip_address": "202.65.173.36",
  "other_currency": "230.00",
  "pg_txnid": "AAM1711030571202459",
  "epw_txnid": "AAM1711030571202459",
  "mer_txnid": "test7572338",
  "store_id": "aamarpaytest",
  "merchant_id": "aamarpaytest",
  "currency": "BDT",
  "store_amount": "225.17",
  "pay_time": "2024-03-21 20:27:23",
  "amount": "230.00",
  "bank_txn": "1019321410400",
  "card_type": "bKash-bKash",
  "reason": "Not Available",
  "pg_card_risklevel": "0",
  "pg_error_code_details": "Not Available",
  "opt_a": null,
  "opt_b": null,
  "opt_c": null,
  "opt
  "opt_a" : "'.$request->c_country.'",  //subtotal
                    "opt_b" : "'.$request->c_city.'",/payment_type
                    "opt_c" :"'.$request->c_phone.'",//customer phone
                    "opt_d" : "'.$request->c_address.'",
                    "opt_e" : "'.Auth::id().'",
                    "ship_name" : "ship name", //ship name
                    "ship_add1" : "House B-121, Road 21",  //ship address
                    "ship_add2" : "Mohakhali",
                    "ship_city" : "Dhaka", 
                    "ship_state" : "Dhaka",
                    "ship_postcode" : "1212", 
                    "ship_country" : "Bangladesh",


                    "ship_name": "ship name",
                    "ship_add1": "House B-121, Road 21",
                    "ship_add2": "Mohakhali",
                    "ship_city": "Dhaka",
                    "ship_state": "Dhaka",
                    "ship_postcode": "1212",
                    "ship_country": "Bangladesh",
